name: Build Windows Installer

on:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: 3.9

permissions:
  contents: write

jobs:
  build:
    name: Build Windows EXE
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache Python dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ./.cache/pip
        key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-deps
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
        
    - name: Install PyInstaller
      run: |
        pip install pyinstaller
        
    - name: Build Application Directory
      run: |
        pyinstaller --onedir --windowed --name MedicalOfficeApp --hidden-import babel.numbers --hidden-import babel.dates --hidden-import json --hidden-import sqlite3 --hidden-import logging app.py
        
    - name: Download Inno Setup
      run: |
        curl -L -o innosetup.exe "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe"
      shell: bash

    - name: Install Inno Setup
      run: |
        ./innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
        echo "C:\Program Files (x86)\Inno Setup 6" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      shell: powershell

    - name: Create Inno Setup Script
      run: |
        @echo off
        (
          echo [Setup]
          echo AppName=Medical Office App
          echo AppVersion=1.0
          echo DefaultDirName={autopf}\Medical Office App
          echo DefaultGroupName=Medical Office App
          echo OutputDir=.\dist
          echo OutputBaseFilename=MedicalOfficeSetup
          echo Compression=lzma
          echo SolidCompression=yes
          echo WizardStyle=modern
          echo UninstallDisplayIcon={app}\MedicalOfficeApp.exe
          echo.
          echo [Languages]
          echo Name: "english"; MessagesFile: "compiler:Default.isl"
          echo.
          echo [Tasks]
          echo Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
          echo.
          echo [Files]
          echo Source: "dist\MedicalOfficeApp\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
          echo ; NOTE: Don't use "Flags: ignoreversion" on any shared system files
          echo.
          echo [Icons]
          echo Name: "{group}\Medical Office App"; Filename: "{app}\MedicalOfficeApp.exe"
          echo Name: "{group}\{cm:UninstallProgram,Medical Office App}"; Filename: "{uninstallexe}"
          echo Name: "{autodesktop}\Medical Office App"; Filename: "{app}\MedicalOfficeApp.exe"; Tasks: desktopicon
          echo.
          echo [Run]
          echo Filename: "{app}\MedicalOfficeApp.exe"; Description: "{cm:LaunchProgram,Medical Office App}"; Flags: nowait postinstall skipifsilent
        ) > installer.iss
      shell: cmd

    - name: Compile Installer with Inno Setup
      run: |
        iscc installer.iss
      shell: cmd

    - name: Upload Installer Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-installer
        path: dist/MedicalOfficeSetup.exe

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/MedicalOfficeSetup.exe
      
    - name: Error handling and cleanup
      if: failure()
      run: |
        echo "Build failed. Cleaning up..."
        if (Test-Path dist) { Remove-Item -Recurse -Force dist }
      shell: powershell
        
    - name: Status report
      run: |
        echo "Build completed successfully!"
